language: R
r:
  - oldrel
  - release
  - devel
sudo: required

before_install:
### GDAL
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo aptitude install -y gdal-bin
  - sudo aptitude install -y libgdal1-dev
  - sudo aptitude install -y libproj-dev
### ImageMagick & FFMPEG
  - sudo apt-get install libudunits2-dev libssh2-1-dev
#  - sudo apt-get install imagemagick cargo libavformat-dev libavcodec-dev
#  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-3
#  - sudo apt-get update
#  - sudo apt-get install -y libavfilter-dev
#  - sudo add-apt-repository -y ppa:opencpu/imagemagick
#  - sudo apt-get update
#  - sudo apt-get install -y libmagick++-dev
### R packages
  - R -e 'install.packages("devtools")'
  - R -e 'install.packages("covr")'

r_github_packages:
  - r-lib/covr

install:
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD check *tar.gz

after_success:
  - Rscript -e 'covr::codecov()'
