language: R
cache: packages

before_install:
  - R -e 'install.packages("devtools")'
  - R -e 'install.packages("covr")'

r_github_packages:
  - munterfinger/eRTG3D

install:
  - R -e 'devtools::install_deps(dep = TRUE)'

script:
  - R CMD build .
  - R CMD check *tar.gz

after_success:
  - Rscript -e 'covr::codecov()'
