language: R

r:
  - oldrel
  - release
  - devel

cache:
  - packages

sudo: required

before_install:
### apt-get
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo aptitude install -y gdal-bin
  - sudo aptitude install -y libgdal1-dev
  - sudo aptitude install -y libproj-dev
  - sudo apt-get install libudunits2-dev libssh2-1-dev
### R packages
  - R -e 'install.packages("devtools")'
  - R -e 'install.packages("covr")'

install:
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD check *tar.gz

after_success:
  - Rscript -e 'covr::codecov()'
